name: check powi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-powi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run check_powi
        run: |
          python .github/workflows/check_powi.py .
