name: "clang-tidy"

on: [pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  clang_tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get AMReX
        run: |
          mkdir external
          cd external
          git clone https://github.com/AMReX-Codes/amrex.git
          cd amrex
          git checkout development
          echo 'AMREX_HOME=$(GITHUB_WORKSPACE)/external/amrex' >> $GITHUB_ENV
          echo $AMREX_HOME
          if [[ -n "${AMREX_HOME}" ]]; then exit 1; fi
          cd ../..

      - name: Get Microphysics
        run: |
          cd external
          git clone https://github.com/AMReX-Astro/Microphysics.git
          cd Microphysics
          git checkout development
          echo 'MICROPHYSICS_HOME=$(GITHUB_WORKSPACE)/external/Microphysics' >> $GITHUB_ENV
          echo $MICROPHYSICS_HOME
          if [[ -n "${MICROPHYSICS_HOME}" ]]; then exit 1; fi
          cd ../..

      - name: Install dependencies
        run: |
          .github/workflows/dependencies_clang-tidy-apt-llvm.sh 17

      - name: Compile convective_grad
        run: |
          cd source/convective_grad
          make USE_MPI=FALSE USE_CLANG_TIDY=TRUE CLANG_TIDY=clang-tidy-17 CLANG_TIDY_WARN_ERROR=TRUE CLANG_TIDY_IGNORE_SOURCES="${MICROPHYSICS_HOME} ${AMREX_HOME}" -j 4

      - name: Compile eos_demo
        run: |
          cd source/eos_demo
          make USE_MPI=FALSE USE_CLANG_TIDY=TRUE CLANG_TIDY=clang-tidy-17 CLANG_TIDY_WARN_ERROR=TRUE CLANG_TIDY_IGNORE_SOURCES="${MICROPHYSICS_HOME} ${AMREX_HOME}" -j 4

      - name: Compile fluxes
        run: |
          cd source/fluxes
          make USE_MPI=FALSE USE_CLANG_TIDY=TRUE CLANG_TIDY=clang-tidy-17 CLANG_TIDY_WARN_ERROR=TRUE CLANG_TIDY_IGNORE_SOURCES="${MICROPHYSICS_HOME} ${AMREX_HOME}" -j 4

      - name: Compile max_enuc
        run: |
          cd source/max_enuc
          make USE_MPI=FALSE USE_CLANG_TIDY=TRUE CLANG_TIDY=clang-tidy-17 CLANG_TIDY_WARN_ERROR=TRUE CLANG_TIDY_IGNORE_SOURCES="${MICROPHYSICS_HOME} ${AMREX_HOME}" -j 4

