name: codespell

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"

      - name: Install dependencies
        run: pip install codespell

      - name: Run codespell
        run: |
          codespell

